#!/usr/bin/env python3
# Copyright (c) ByteDance Ltd. and/or its affiliates.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Copyright (c) ByteDance Ltd. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import argparse
import os
import sys
from pathlib import Path

import yaml


GENERATED_HEADER = (
    "# This file was generated by Conan. Remove this comment if you edit this file or Conan\n"
    "# will destroy your changes.\n"
)
DEFAULT_PROFILE_NAME = "default"
PROFILE_TEMPLATE_PREAMBLE = [
    "{% set libc, libc_version = detect_api.detect_libc() %}",
]
PROFILE_TEMPLATE_SETTINGS = [
    "{% if libc %}",
    "os.libc={{ libc }}",
    "{% endif %}",
    "{% if libc_version %}",
    "os.libc_version={{ libc_version }}",
    "{% endif %}",
]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Update Conan settings_user.yml to support os.libc/os.libc_version. "
            "When run without arguments, it updates $CONAN_HOME/profiles/default. "
            "Use --profile <name> to update a different profile."
        )
    )
    parser.add_argument(
        "--profile",
        default=None,
        help=(
            "Conan profile name to update. Default: default. "
            "If omitted, direct execution updates $CONAN_HOME/profiles/default."
        ),
    )
    parser.add_argument(
        "--skip-profile",
        action="store_true",
        help="Only update settings_user.yml, do not touch any profile",
    )
    return parser.parse_args()


def strip_generated_header(text: str) -> str:
    if text.startswith(GENERATED_HEADER):
        return text[len(GENERATED_HEADER) :]
    return text


def update_settings_user_file(settings_user_file: Path) -> None:
    if settings_user_file.exists():
        data = yaml.safe_load(settings_user_file.read_text()) or {}
    else:
        data = {}

    os_settings = data.setdefault("os", {})
    linux_settings = os_settings.setdefault("Linux", {})
    if linux_settings is None:
        linux_settings = {}
        os_settings["Linux"] = linux_settings

    linux_settings["libc"] = [None, "gnu", "musl"]
    linux_settings["libc_version"] = [None, "ANY"]
    settings_user_file.write_text(yaml.safe_dump(data, sort_keys=False))


def update_profile_with_libc_template(profile_file: Path, profile_name: str) -> None:
    lines = profile_file.read_text().splitlines() if profile_file.exists() else []

    output: list[str] = []
    in_settings = False
    settings_seen = False
    inserted = False

    for line in lines:
        if line in PROFILE_TEMPLATE_PREAMBLE:
            continue

        stripped = line.strip()
        is_section = stripped.startswith("[") and stripped.endswith("]")

        if stripped == "[settings]":
            settings_seen = True
            in_settings = True
            output.append(line)
            continue

        if is_section:
            if in_settings and not inserted:
                output.extend(PROFILE_TEMPLATE_SETTINGS)
                inserted = True
            in_settings = False
            output.append(line)
            continue

        if in_settings and (
            line in PROFILE_TEMPLATE_SETTINGS
            or line.startswith("os.libc=")
            or line.startswith("os.libc_version=")
        ):
            continue

        output.append(line)

    if not settings_seen:
        output = ["[settings]", *PROFILE_TEMPLATE_SETTINGS, "", *output]
    elif in_settings and not inserted:
        output.extend(PROFILE_TEMPLATE_SETTINGS)

    while output and output[0] == "":
        output.pop(0)

    output = [*PROFILE_TEMPLATE_PREAMBLE, "", *output]

    profile_file.parent.mkdir(parents=True, exist_ok=True)
    profile_file.write_text("\n".join(output).rstrip() + "\n")


def update_selected_profile(profile_file: Path, profile_name: str) -> None:
    print(f"🔧 Updating Conan profile: {profile_file}")
    update_profile_with_libc_template(profile_file, profile_name)
    print(
        f"✅ Profile '{profile_name}' updated to resolve "
        "os.libc/os.libc_version from detect_api.detect_libc()"
    )


def main() -> int:
    args = parse_args()
    conan_home = Path(os.environ.get("CONAN_HOME", "~/.conan2")).expanduser()
    settings_file = conan_home / "settings.yml"
    settings_user_file = conan_home / "settings_user.yml"

    if not settings_file.is_file():
        print(f"❌ Conan settings file not found: {settings_file}", file=sys.stderr)
        return 1

    print(f"🔧 Updating Conan user settings file: {settings_user_file}")
    update_settings_user_file(settings_user_file)
    print(
        "✅ Added Linux settings override to settings_user.yml: os.libc / os.libc_version"
    )

    if args.skip_profile:
        print("ℹ️  Skipped profile update by request")
        return 0

    profile_name = args.profile or DEFAULT_PROFILE_NAME

    profile_file = conan_home / "profiles" / profile_name
    update_selected_profile(profile_file, profile_name)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
